# Generated by Django 5.0.2 on 2024-02-28 20:17

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(help_text='Enter a phone number with digits and + only.', max_length=15, unique=True, validators=[user_profile.models.validate_phone_number]),
        ),
    ]
